[package]
name = "spicy-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
channel_io = "0.1.3"
flume = "0.11.0"
tower = "0.5.1"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
